# Version Check
If you followed the advice outlined in the introduction lecture and installed the Anaconda stack,
you already have NumPy installed and ready to go. If you’re more the do-it-yourself
type, you can go to the NumPy website and follow the installation instructions found
there

In [ ]:
!pip install numpy

In [1]:
import numpy
numpy.__version__

'1.18.5'

Recommend NumPy version 1.8 or
later. 
By convention, you’ll find that most people import NumPy using np as an alias:

In [2]:
import numpy as np

# Creating Arrays from Python Lists

In [3]:
lst=[1,3,5,7]
np.array(lst)


array([1, 3, 5, 7])

In [4]:
np.array(lst, dtype='float32')
#To set the data type of the resulting array, we can use the dtype keyword

array([1., 3., 5., 7.], dtype=float32)

# Creating Arrays from Scratch
    

In [5]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [8]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.54314725, 0.02300533, 0.17605503],
       [0.66887744, 0.44806461, 0.2773297 ],
       [0.38815435, 0.6873034 , 0.69631381]])

In [12]:
# Create a 3x3 array of random integers in the interval [0, 10]
np.random.randint(0, 10, (3, 3))

array([[3, 6, 5],
       [5, 3, 2],
       [6, 9, 9]])

In [13]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# NumPy Array Attributes

In [14]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array


Each array has attributes ndim (the number of dimensions), shape (the size of each
dimension), and size (the total size of the array)

In [15]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Another useful attribute is the dtype, the data type of the array

In [16]:
print("dtype:", x3.dtype)

dtype: int32


Other attributes include itemsize, which lists the size (in bytes) of each array element,
and nbytes, which lists the total size (in bytes) of the array

In [17]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


# Array Indexing: Accessing Single Elements

If you are familiar with Python’s standard list indexing, indexing in NumPy will feel
quite familiar.

In [18]:
print(x1)
x1[0],x1[4]


[5 0 3 3 7 9]


(5, 7)

In [19]:
x1[-1],x1[-2]

(9, 7)

In [20]:
print(x2)
x2[0, 3]

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


4

# Array Slicing: Accessing Subarrays
The NumPy slicing syntax follows that of the standard Python list; to access a slice of
an array x, use this:

x[start:stop:step]

In [21]:
x = np.arange(10)
print(x)
print(x[:5])# first five elements
print(x[5:])# elements after index 5
print(x[4:7]) # middle subarray

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]


In [22]:
#Multidimensional subarrays
print(x2)
print(x2[:2, :3])# two rows, three columns
print(x2[:3, ::2]) # all rows, every other column

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5 2]
 [7 6 8]]
[[3 2]
 [7 8]
 [1 7]]


# Reshaping of Arrays
Note that for this to work, the size of the initial array must match the size of the
reshaped array

In [23]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Array Concatenation and Splitting

In [24]:
##Concatenation of arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [26]:
#np.concatenate can also be used for two-dimensional arrays
grid = np.array([[1, 2, 3],
[4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [27]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [30]:
#For working with arrays of mixed dimensions, it can be clearer to use the np.vstack
#(vertical stack) and np.hstack (horizontal stack) functions:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [31]:
# horizontally stack the arrays
y = np.array([[99],
[99]])
np.hstack([grid, y])
#Similarly, np.dstack will stack arrays along the third axis.

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

The opposite of concatenation is splitting, which is implemented by the functions
np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices
giving the split points

In [32]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [33]:
grid = np.arange(16).reshape((4, 4))
print(grid)
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [34]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
